
* Alsa,Jack, Pulseaudio and Systemd User Sessions

* Alsa Setup

  These are the cards for my hardware:

#+BEGIN_SRC sh
  cat /sys/class/sound/card*/id
#+END_SRC

  - Nvidia  :: NVIDIA HDMI, Card 0, 4 Devices
  - Generic :: Motherboard HD Audio (ALC 1220), Card 1, 2 Devices
  - Adapter :: USB Rocksmith Guitar Adapter, Card 2, 1 Device
  - USB     :: Focusrite Scarlet 8i6 in, Card 3, 1 Device

  and here is the configuration for kernel modules and alsa.
  The kernel module options make sure that the modules are loaded in
  the same order every boot.
  
#+BEGIN_EXAMPLE /etc/modprobe.d/alsa.conf
# Alsa kernel modules' configuration file.

# ALSA portion
alias char-major-116 snd
options snd major=116 cards_limit=5 slots=snd_aloop,snd_hda_intel,snd_hda_intel,snd_usb_audio,snd_usb_audio

# Loopback
alias snd-card-0 snd_aloop
options snd_aloop index=0

# Internal Audio and NVidia HDMI Audio
alias snd-card-1 snd_hda_intel
alias snd-card-2 snd_hda_intel
options snd_hda_intel index=1,2

# USB: index 3 = Scarlett 8i6, 4 = Rocksmith Adaptor
alias snd-card-3 snd_usb_audio
alias snd-card-4 snd_usb_audio
options snd_usb_audio index=3,4 vid=0x1235,0x12ba pid=0x8002,0x00ff

#+END_EXAMPLE

   The alsa config snippet gives some nicer names to the hardware
   cards. We use these later. 
   
#+BEGIN_EXAMPLE /etc/alsa/conf.d/99-cards.conf
pcm.hdmi0 {
    type hw
    card NVidia
    device 0
    hint.description "HDMI Audio Output"
}

ctl.hdmi0 {
    type hw
    card NVidia
    device 0
}

pcm.hdmi1 {
    type hw
    card NVidia
    device 1
    hint.description "HDMI Audio Output"
}

ctl.hdmi1 {
    type hw
    card NVidia
    device 1
}

pcm.hdmi2 {
    type hw
    card NVidia
    device 2
    hint.description "HDMI Audio Output"
}

ctl.hdmi2 {
    type hw
    card NVidia
    device 2
}

pcm.hdmi3 {
    type hw
    card NVidia
    device 3
    hint.description "HDMI Audio Output"
}

ctl.hdmi3 {
    type hw
    card NVidia
    device 3
}

pcm.analog {
    type hw
    card Generic
    device 0
    hint.description "Internal HD audio, analog"
}

ctl.analog {
    type hw
    card Generic
    device 0
}

pcm.digital {
    type hw
    card Generic
    device 1
    hint.description "Internal HD audio, optical digital"
}

ctl.digital {
    type hw
    card Generic
    device 1
}

pcm.scarlett {
    type hw
    card USB
    device 0
    hint.description "Focusrite Scarlett 8i6 USB"
}

ctl.scarlett {
    type hw
    card USB
    device 0
}

pcm.rocksmith {
    type hw
    card Adapter
    device 0
    hint.description "Rocksmith USB Adapter"
}

ctl.rocksmith {
    type hw
    card Adapter
    device 0
}

pcm.default pulse
ctl.default pulse

#+END_EXAMPLE

* Jack

  In case jack can not switch to realtime mode when started from a
  user session systemd service, but does it just fine from the X11
  session dbus, check if /etc/pam.d/systemd-user contains the line

: session required pam_limits.so

  
* Pulseaudio

  I want Pulsaudio for the ease of integrating non Jack-aware desktop
  applications. It is bridged to Jack via module-jack-source and module-jack-sink.
  Pulseaudio can not set realtime scheduling for the jack modules,
  there is an open issue for this in the bugtracker.
